version: "3"
services:
  dweller:
    build: ./packages/dweller-cli
    entrypoint:
      - npx
      - nodemon
      - src/cli
    depends_on:
      - kafka
    env_file:
      - .env.composition
    volumes:
      - ./packages/dweller-cli/test/fixtures:/usr/share/dweller/scripts
      - ./packages/dweller-cli:/usr/share/app
      - /usr/share/app/node_modules
    networks:
      - app-tier
  zookeeper:
    image: 'bitnami/zookeeper:3.6.2'
    hostname: zookeeper
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - app-tier
  kafka:
    image: 'bitnami/kafka:2.7.0'
    environment:
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    healthcheck:
      test:
        [ "CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181" ]
      interval: 30s
      timeout: 10s
      retries: 4
    networks:
      - app-tier
    depends_on:
      - zookeeper

networks:
  app-tier:
